# Generated by Django 4.2.6 on 2023-11-18 08:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="user",
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        decimal_places=2, default=10000.0, max_digits=10
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="expense",
            name="user_profile",
            field=models.ForeignKey(
                default=1000,
                on_delete=django.db.models.deletion.CASCADE,
                to="app_users.userprofile",
            ),
            preserve_default=False,
        ),
    ]
