# Generated by Django 4.2.6 on 2023-11-18 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app_users", "0002_remove_expense_user_userprofile_expense_user_profile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="expense",
            name="user_profile",
        ),
        migrations.AddField(
            model_name="expense",
            name="user",
            field=models.ForeignKey(
                default=1000,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
